defaults:
  - default

_target_: lightning.pytorch.Trainer
max_epochs: 500
accelerator: ${device.accelerator}
devices: ${device.devices}
precision: 32
gradient_clip_val: 1.0
val_check_interval: 1.0
log_every_n_steps: 10
enable_progress_bar: true
enable_model_summary: true


logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  name: ${name}
  save_dir: "outputs/${name}"  # Use absolute path from current working directory

callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: "outputs/${name}/checkpoints"  # Use absolute path
      filename: "epoch={epoch:03d}-step={step}-val_loss={val_loss:.6f}"
      monitor: "val_loss"
      mode: "min"
      save_top_k: 3
      save_last: true
      every_n_epochs: 1
      save_on_train_epoch_end: false
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: "val_loss"
      mode: "min"
      patience: 50
      min_delta: 1e-6
      verbose: true