defaults:
  - default

_target_: lightning.pytorch.Trainer
max_epochs: 500
accelerator: ${device.accelerator}
devices: ${device.devices}
precision: 32
gradient_clip_val: 1.0
val_check_interval: 1.0
log_every_n_steps: 10
enable_progress_bar: true
enable_model_summary: true