# @package _global_
sampling_mode: conformal
acquisition:
  _target_: adaptive_roa.adaptive_v2.strategy.conformal.ConformalAcquisitionStrategy
  d2_ratio: 0.5
  batch_size_sampling: 50
  max_samples_per_epoch: 50000
  decision_rule: ${decision_rule}
  verbose: true
