# @package _global_.system
# =====================================================================
# Humanoid System Configuration
# =====================================================================
# Humanoid dynamics with ℝ³⁴ × S² × ℝ³⁰ manifold structure
# State: 67-dimensional vector where:
#   - dims 0-33: Euclidean (positions, velocities, joint angles)
#   - dims 34-36: Sphere (orientation as 3D unit vector, norm=1)
#   - dims 37-66: Euclidean (additional joint states)
#
# Task: Get-up (humanoid standing from prone/supine position)
# =====================================================================

_target_: src.systems.humanoid.HumanoidSystem

# Data bounds configuration (optional)
bounds_file: null  # Set to path if you have precomputed bounds
use_dynamic_bounds: false  # If false, uses default fallback bounds
