# Configuration for Humanoid Latent Conditional UNet model
_target_: src.model.universal_unet.UniversalUNet

# Humanoid-specific dimensions
# Manifold: ℝ³⁴ × S² × ℝ³⁰ (67-dimensional state)
# - Dims 0-33: Euclidean (34 dims)
# - Dims 34-36: Sphere (3 dims) - 3D unit vector
# - Dims 37-66: Euclidean (30 dims)

input_dim: 142         # embedded(67) + condition(67) + latent(8)
output_dim: 67         # 67-dimensional velocity in tangent space
time_embed_dim: 128    # Time embedding dimension

# Architecture - deeper for high-dimensional space
hidden_dims: [256, 512, 512, 256]
dropout: 0.1
activation: silu       # SiLU/Swish activation (smooth, works well with flow matching)
