_target_: src.model.mlp.MLP
# Input = [sinθ, cosθ, ω]=3 + t=1 + [sinθ0, cosθ0, ω0]=3 + z=L => 7+L = 15 (for L=8)
input_dim: 15  # 7 + 8 (latent_dim)
output_dim: 2
hidden_channels: [128, 256, 256, 128]