_target_: src.module.simple_mlp.SimpleMLP
model:
  _target_: src.model.mlp.MLP
  input_dim: 8
  output_dim: 1
  hidden_channels: [512, 512, 512]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: ${base_lr}
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.5
  patience: 10
  min_lr: 0.000001