# @package _global_
# Pendulum LQR 50k dataset paths

data_dirs: /common/users/dm1487/arcmg_datasets/pendulum_lqr/pendulum_lqr_50k
dest_dir: /common/users/dm1487/arcmg_datasets/pendulum_lqr/pendulum_lqr_50k/endpoint_dataset
