model_config:
  _target_: src.model.pendulum_cartesian_unet.PendulumCartesianUNet
  embedded_dim: 4
  latent_dim: 2
  condition_dim: 4
  time_emb_dim: 128
  hidden_dims:
  - 256
  - 512
  - 512
  - 256
  output_dim: 4
  use_input_embeddings: false
  input_emb_dim: 128
latent_dim: 2
mae_val_frequency: 10
