# =====================================================================
# Sampled Endpoint Dataset Builder Configuration
# =====================================================================
# Builds endpoint dataset by randomly sampling N trajectories
#
# Usage:
#   python src/build_sampled_endpoint_dataset.py
#   python src/build_sampled_endpoint_dataset.py system=cartpole
#   python src/build_sampled_endpoint_dataset.py sample_points=100
# =====================================================================

defaults:
  - system: pendulum

data_dirs: /common/users/dm1487/arcmg_datasets/pendulum_lqr/pendulum_lqr50k/pendulum_lqr50k
dest_dir: /common/users/dm1487/arcmg_datasets/pendulum_lqr/sampled_endpoint_dataset
sample_points: 50  # Number of trajectories to randomly sample