# Build cartpole endpoint dataset from trajectory files
# Creates (start_state, attractor_state) pairs for LCFM training

system:
    _target_: src.systems.cartpole_lcfm.CartPoleSystemLCFM

# CartPole data paths
data_dirs: /common/users/shared/pracsys/genMoPlan/data_trajectories/cartpole/trajectories
shuffled_idxs_file: /common/users/shared/pracsys/genMoPlan/data_trajectories/cartpole/shuffled_indices.txt
dest_dir: /common/users/dm1487/arcmg_datasets/cartpole/incremental_endpoint_dataset

# Number of trajectories to process (start small for testing)
increment: 500
type: train # test set only samples 1 start and end state per trajectory; train and val sample len(trajectories) - 1 start points and 1 end point per trajectory
start: 0
end: 500