# Build cartpole endpoint dataset from trajectory files
# Creates (start_state, attractor_state) pairs for LCFM training

system:
    _target_: src.systems.cartpole_lcfm.CartPoleSystemLCFM

# CartPole data paths
data_dirs: /common/users/shared/pracsys/genMoPlan/data_trajectories/cartpole/trajectories
shuffled_idxs_file: /common/users/shared/pracsys/genMoPlan/data_trajectories/cartpole/shuffled_indices.txt
dest_dir: /common/users/dm1487/arcmg_datasets/cartpole/incremental_endpoint_dataset_fixed_attractors

# Number of trajectories to process (start small for testing)
increment: 10
type: train # test set only samples 1 start and end state per trajectory; train and val sample len(trajectories) - 1 start points and 1 end point per trajectory
start: 0
end: 10

# Fixed attractor endpoints
# If true, use fixed attractors: [0,0,0,0] for success, [0,Ï€,0,0] for failure
# If false, use actual trajectory endpoints
use_fixed_attractors: true

# Attractor radius for success/failure classification (default: 0.1)
# Used by system.is_in_attractor() to determine if final state is successful
attractor_radius: 0.1

# Balance dataset between success/failure endpoints (only for train/val, not test)
# If true, randomly sample equal numbers of success and failure endpoints
balance_dataset: false