defaults:
  - _self_
  - device: gpu1  # Default to GPU 1

# Demo configuration
checkpoint_path: "outputs/2025-07-26/03-56-35/lightning_logs/version_0/checkpoints/epoch=499-step=29500.ckpt"

# Analysis settings
analysis:
  resolutions: [0.2, 0.1, 0.05]  # Different resolutions to test
  batch_size: 500
  output_dir: "attractor_analysis_results"