# CartPole Gaussian Noise ROA Evaluation Configuration
# Evaluates trained Gaussian Noise FM model on labeled ROA data

name: cartpole_gaussian_roa_evaluation
seed: 42

# System configuration - Gaussian Noise variant
system:
  module: src.flow_matching.cartpole.gaussian_noise.flow_matcher
  class: CartPoleGaussianNoiseFlowMatcher

# Checkpoint to evaluate
checkpoint:
  path: null  # Auto-find latest if null
  auto_find: true  # Search for latest checkpoint
  base_name: cartpole_gaussian_noise_fm  # Used for auto-finding

# Data: Labeled ROA data
data:
  file: /common/users/shared/pracsys/genMoPlan/data_trajectories/cartpole/roa_labels.txt
  format: "x θ ẋ θ̇ label"  # Space-separated format

# Evaluation settings
evaluation:
  batch_size: 500
  num_steps: 100  # ODE integration steps
  attractor_radius: 0.3  # Success threshold

  # Probabilistic mode (uncertainty estimation)
  probabilistic: true
  num_samples: 20  # Only used if probabilistic=true

# Output
output:
  dir: cartpole_gaussian_roa_evaluation
  save_plots: true
  save_data: true

# Hydra output directory
hydra:
  run:
    dir: outputs/${name}/${now:%Y-%m-%d_%H-%M-%S}
