# Pendulum ROA Evaluation Configuration
# Evaluates trained LCFM model on labeled ROA data

name: pendulum_roa_evaluation
seed: 42

# System configuration
system:
  module: src.flow_matching.pendulum.latent_conditional.flow_matcher
  class: PendulumLatentConditionalFlowMatcher

# Checkpoint to evaluate
checkpoint:
  path: null  # Auto-find latest if null
  auto_find: true  # Search for latest checkpoint
  base_name: pendulum_latent_conditional_fm  # Used for auto-finding

# Data: Labeled ROA data
data:
  file: /common/users/shared/pracsys/genMoPlan/data_trajectories/pendulum_lqr_50k/roa_labels_700k_DO_NOT_USE_DEATH_INSIDE.txt
  format: "θ θ̇ label"  # Space-separated format

# Evaluation settings
evaluation:
  batch_size: 10000
  num_steps: 100  # ODE integration steps
  attractor_radius: 0.1  # Success threshold

  # Probabilistic mode (uncertainty estimation)
  probabilistic: true
  num_samples: 50  # Only used if probabilistic=true

  # Two-threshold classification strategy:
  # - Success: p_stable > success_threshold (confident success)
  # - Failure: p_stable < failure_threshold (confident failure)
  # - Separatrix: failure_threshold <= p_stable <= success_threshold (uncertain)
  success_threshold: 0.9  # Minimum proportion for declaring success (>90%)
  failure_threshold: 0.5  # Maximum proportion for declaring failure (<50%)

# Output
output:
  dir: pendulum_roa_evaluation
  save_plots: true
  save_data: true

# Hydra output directory
hydra:
  run:
    dir: outputs/${name}/${now:%Y-%m-%d_%H-%M-%S}
