# CartPole ROA Evaluation Configuration
# Evaluates trained LCFM model on labeled ROA data

name: cartpole_roa_evaluation
seed: 42

# System configuration
system:
  module: src.flow_matching.cartpole_latent_conditional.flow_matcher_fb
  class: CartPoleLatentConditionalFlowMatcher

# Checkpoint to evaluate
checkpoint:
  path: /common/home/dm1487/robotics_research/tripods/olympics-classifier/outputs/cartpole_latent_conditional_fm/2025-10-13_02-11-56  # Auto-find latest if null
  auto_find: true  # Search for latest checkpoint
  base_name: cartpole_latent_conditional_fm  # Used for auto-finding

# Data: Labeled ROA data
data:
  file: /common/users/shared/pracsys/genMoPlan/data_trajectories/cartpole/roa_labels.txt
  format: "x θ ẋ θ̇ label"  # Space-separated format

# Evaluation settings
evaluation:
  batch_size: 500
  num_steps: 100  # ODE integration steps
  attractor_radius: 0.3  # Success threshold

  # Probabilistic mode (uncertainty estimation)
  probabilistic: true
  num_samples: 20  # Only used if probabilistic=true

# Output
output:
  dir: cartpole_roa_evaluation
  save_plots: true
  save_data: true

# Hydra output directory
hydra:
  run:
    dir: outputs/${name}/${now:%Y-%m-%d_%H-%M-%S}
