defaults:
  - _self_
  - data: circular_endpoint_data
  - model: circular_flow_matching_unet
  - module: circular_flow_matching
  - optimizer: adamw
  - scheduler: reduce_lr_on_plateau
  - trainer: flow_matching
  - device: gpu1

seed: 42
num_workers: 4
batch_size: 128