defaults:
    - _self_
    - data: classifier_data
    # - model: vae
    # - trainer: gpu

seed: 42
num_workers: 4
batch_size: 16

# trainer
max_epochs: 1000
check_val_every_n_epoch: 10

base_lr: 0.01
end_lr: 0.000001
warmup_steps: 1000
decay_steps: 300000
