defaults:
  - _self_
  - device: gpu1
  - data: circular_endpoint_data
  - model: latent_circular_unet
  - module: latent_circular_flow_matching
  - optimizer: adamw
  - scheduler: null
  - trainer: default

seed: 42
sigma: 0.0
num_integration_steps: 100
batch_size: 256
num_workers: 4