defaults:
  - _self_
  - data: endpoint_data
  - model: flow_matching_unet
  - module: standard_flow_matching
  - optimizer: adamw  
  - scheduler: reduce_lr_on_plateau
  - trainer: flow_matching
  - device: gpu1

seed: 42
num_workers: 4
batch_size: 256

# Override trainer epochs for standard flow matching
trainer:
  max_epochs: 200