# @package model_dims

embedded_dim: 7
condition_dim: 7
output_dim: 6
time_emb_dim: 64

unet_target: adaptive_roa.model.quadrotor2d_unet.Quadrotor2DUNet
unet_hidden_dims: [256, 512, 1024, 512, 256]

mlp_hidden_dims: [256, 512, 1024, 512, 256]

adaln_hidden_dim: 384
adaln_num_blocks: 6
adaln_cond_dim: 192
adaln_mlp_ratio: 2
adaln_dropout: 0.0

dit_hidden_dim: 192
dit_num_blocks: 4
dit_num_heads: 4
dit_cond_dim: 192
dit_mlp_ratio: 4
dit_dropout: 0.0

use_input_embeddings: false
input_emb_dim: 64
