# @package model_dims

embedded_dim: 13
condition_dim: 13
output_dim: 12
time_emb_dim: 64

unet_target: adaptive_roa.model.quadrotor3d_unet.Quadrotor3DUNet
unet_hidden_dims: [512, 1024, 1024, 512]

mlp_hidden_dims: [512, 1024, 1024, 512]

adaln_hidden_dim: 512
adaln_num_blocks: 8
adaln_cond_dim: 256
adaln_mlp_ratio: 2
adaln_dropout: 0.0

dit_hidden_dim: 256
dit_num_blocks: 6
dit_num_heads: 4
dit_cond_dim: 256
dit_mlp_ratio: 4
dit_dropout: 0.0

use_input_embeddings: false
input_emb_dim: 128
