# @package model

_target_: adaptive_roa.model.simple_flow_mlp.SimpleFlowMLP

embedded_dim: ${model_dims.embedded_dim}
latent_dim: ${flow_matching.latent_dim}
condition_dim: ${model_dims.condition_dim}
time_emb_dim: ${model_dims.time_emb_dim}
hidden_dims: ${model_dims.mlp_hidden_dims}
output_dim: ${model_dims.output_dim}
use_input_embeddings: ${model_dims.use_input_embeddings}
input_emb_dim: ${model_dims.input_emb_dim}
