"""Lint experiment cards under docs/experiments/ and regenerate the dashboard.

Stdlib only: must run without PyYAML. Frontmatter is a restricted subset —
`key: value` scalars and inline `[a, b]` / `[]` lists, one per line.
"""
from __future__ import annotations

VALID_STATUS = ["idea", "live", "done"]
REQUIRED_SECTIONS = ["Hypothesis", "Plan", "Run", "Result + Verdict", "Next", "Discussion"]
INDEX_ROUTE = "experiments/WORKFLOW.md"


def split_frontmatter(text):
    """Return (frontmatter_dict_or_None, body_text)."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None, text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            fm = _parse_block(lines[1:i])
            body = "\n".join(lines[i + 1:])
            return fm, body
    return None, text


def _parse_block(block_lines):
    fm = {}
    for line in block_lines:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, raw = line.partition(":")
        key = key.strip()
        val = raw.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            fm[key] = [p.strip() for p in inner.split(",") if p.strip()] if inner else []
        else:
            fm[key] = val
    return fm


def parse_frontmatter(text):
    fm, _ = split_frontmatter(text)
    return fm


def card_violations(path, text):
    problems = []
    fm, body = split_frontmatter(text)
    if fm is None:
        return [f"{path}: missing YAML frontmatter"]
    if fm.get("type") != "experiment":
        problems.append(f"{path}: frontmatter type must be 'experiment'")
    status = fm.get("status")
    if status not in VALID_STATUS:
        problems.append(f"{path}: status '{status}' not in {VALID_STATUS}")
    if status in ("live", "done") and not fm.get("commit"):
        problems.append(f"{path}: commit SHA required once status is live/done")
    if status in ("live", "done") and not fm.get("metric"):
        problems.append(f"{path}: metric required once status is live/done")
    if status == "done" and not fm.get("splits"):
        problems.append(f"{path}: splits must be non-empty for a done card")
    # Section presence + order.
    last = -1
    for section in REQUIRED_SECTIONS:
        idx = body.find(f"## {section}")
        if idx == -1:
            problems.append(f"{path}: missing section '## {section}'")
        elif idx < last:
            problems.append(f"{path}: section '## {section}' out of order")
        else:
            last = idx
    return problems


def index_violations(index_text):
    if INDEX_ROUTE in index_text:
        return []
    return [f"docs/INDEX.md: missing route to {INDEX_ROUTE}"]


import argparse
import os
import sys

DEFAULT_EXPERIMENTS = os.path.join("docs", "experiments")
DEFAULT_INDEX = os.path.join("docs", "INDEX.md")
_DASH_HEADER = "<!-- generated by scripts/docs_lint.py --dashboard — do not edit by hand -->\n"


def _iter_card_paths(experiments_dir):
    for sub in ("log", "archive"):
        base = os.path.join(experiments_dir, sub)
        if not os.path.isdir(base):
            continue
        for name in sorted(os.listdir(base)):
            if name.endswith(".md"):
                yield os.path.join(base, name)


def collect_cards(experiments_dir):
    cards = []
    for path in _iter_card_paths(experiments_dir):
        with open(path, encoding="utf-8") as f:
            fm, _ = split_frontmatter(f.read())
        rel = os.path.relpath(path, experiments_dir)
        cards.append((rel, fm or {}))
    return sorted(cards, key=lambda c: c[0])


def check_tree(experiments_dir, index_path):
    problems = []
    for path in _iter_card_paths(experiments_dir):
        with open(path, encoding="utf-8") as f:
            problems.extend(card_violations(path, f.read()))
    if os.path.exists(index_path):
        with open(index_path, encoding="utf-8") as f:
            problems.extend(index_violations(f.read()))
    else:
        problems.append(f"{index_path}: file not found")
    return problems


def _cell(fm, key):
    val = fm.get(key, "")
    if isinstance(val, list):
        return ", ".join(val)
    return val or ""


def render_dashboard(cards):
    cols = ["card", "status", "thread", "systems", "predictor", "metric", "verdict"]
    lines = [_DASH_HEADER, "# Experiment Dashboard\n",
             "| " + " | ".join(cols) + " |",
             "|" + "|".join(["---"] * len(cols)) + "|"]
    for rel, fm in cards:
        row = [os.path.basename(rel),
               _cell(fm, "status"), _cell(fm, "thread"), _cell(fm, "systems"),
               _cell(fm, "predictor"), _cell(fm, "metric"), _cell(fm, "verdict")]
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Lint experiment cards; regenerate dashboard.")
    parser.add_argument("--experiments", default=DEFAULT_EXPERIMENTS)
    parser.add_argument("--index", default=DEFAULT_INDEX)
    parser.add_argument("--dashboard", action="store_true", help="regenerate DASHBOARD.md")
    args = parser.parse_args(argv)

    if args.dashboard:
        cards = collect_cards(args.experiments)
        with open(os.path.join(args.experiments, "DASHBOARD.md"), "w", encoding="utf-8") as f:
            f.write(render_dashboard(cards))

    problems = check_tree(args.experiments, args.index)
    for p in problems:
        print(p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
