#!/usr/bin/env python3
"""
Combined CartPole comparison from CSV files: Ground Truth vs Olympics vs DeepReach.

Reads pre-computed results directly from CSV files (no model inference needed):
  - Ground truth: viz_theta_vs_thetadot.csv, viz_x_vs_xdot.csv
  - DeepReach:    deepreach_theta_vs_thetadot.csv, deepreach_x_vs_xdot.csv
  - Olympics:     qualitative_cartpole_<slice>_cache.npz (optional, from plot_qualitative_cartpole.py)

Generates:
  - Individual bare heatmaps per method/slice
  - Combined comparison grid (horizontal + vertical)
  - Error analysis (FP/FN) plots

Usage:
    # GT + DeepReach only (no GPU needed)
    python scripts/plot_csv_comparison.py --all_slices --no_olympics

    # GT + Olympics + DeepReach
    python scripts/plot_csv_comparison.py --all_slices

    # Single slice
    python scripts/plot_csv_comparison.py --slice theta_thetadot
"""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import pandas as pd

# ── Data paths ───────────────────────────────────────────────────────────────
_GT_DIR = Path(
    "/common/users/shared/pracsys/genMoPlan/data_trajectories/cartpole_pybullet"
)
_DR_DIR = Path(
    "/common/users/shared/pracsys/adaptive_roa_experiments/dhruv"
    "/deepreach/cartpole_tc_1000/cartpole_tc"
)

# ── Olympics cache (generated by plot_qualitative_cartpole.py) ────────────────
OLYMPICS_CACHE_DIR = Path("results/figures")
_CACHE_KEY_MAP = {
    "Adaptive (d2=1.0)": "Adaptive (Ours)",
    "Non-adaptive": "Non-adaptive (Ours)",
}
DEFAULT_EPOCH = 15

# ── Slice definitions (ranges match the actual CSV data) ─────────────────────
SLICES = {
    "theta_thetadot": {
        "gt_csv": _GT_DIR / "viz_theta_vs_thetadot.csv",
        "gt_ax0_col": "theta",
        "gt_ax1_col": "theta_dot",
        "dr_csv": _DR_DIR / "deepreach_theta_vs_thetadot.csv",
        "dr_ax0_col": "theta",
        "dr_ax1_col": "thetadot",
        "sweep_ranges": ((-np.pi, np.pi), (-5.0, 5.0)),
        "fixed_label": r"$x{=}{-}1.51,\;\dot{x}{=}0$",
        "xlabel": r"$\theta$ (rad)",
        "ylabel": r"$\dot{\theta}$ (rad/s)",
        "xticks": [-np.pi, -np.pi / 2, 0, np.pi / 2, np.pi],
        "xticklabels": [r"$-\pi$", r"$-\frac{\pi}{2}$", "0",
                        r"$\frac{\pi}{2}$", r"$\pi$"],
        "yticks": [-4, -2, 0, 2, 4],
        "yticklabels": ["-4", "-2", "0", "2", "4"],
    },
    "x_xdot": {
        "gt_csv": _GT_DIR / "viz_x_vs_xdot.csv",
        "gt_ax0_col": "x",
        "gt_ax1_col": "x_dot",
        "dr_csv": _DR_DIR / "deepreach_x_vs_xdot.csv",
        "dr_ax0_col": "x",
        "dr_ax1_col": "xdot",
        "sweep_ranges": ((-6.0, 6.0), (-5.0, 5.0)),
        "fixed_label": r"$\theta{=}{-}0.31,\;\dot{\theta}{=}{-}4.29$",
        "xlabel": r"$x$ (m)",
        "ylabel": r"$\dot{x}$ (m/s)",
        "xticks": [-6, -3, 0, 3, 6],
        "xticklabels": ["-6", "-3", "0", "3", "6"],
        "yticks": [-4, -2, 0, 2, 4],
        "yticklabels": ["-4", "-2", "0", "2", "4"],
    },
}

# ── Output ───────────────────────────────────────────────────────────────────
OUTPUT_DIR = Path("results/figures")
FLAGSHIP_DIR = OUTPUT_DIR / "flagship"


# ═══════════════════════════════════════════════════════════════════════════════
# Data loaders
# ═══════════════════════════════════════════════════════════════════════════════

def load_gt_csv(slice_name: str):
    """Load ground truth CSV. Returns (gt_labels_flat, n0, n1)."""
    sl = SLICES[slice_name]
    df = pd.read_csv(sl["gt_csv"])
    ax0, ax1 = sl["gt_ax0_col"], sl["gt_ax1_col"]
    df = df.sort_values([ax0, ax1]).reset_index(drop=True)
    n0 = df[ax0].nunique()
    n1 = df[ax1].nunique()
    labels = df["label"].values.astype(np.int8)
    print(f"  GT {sl['gt_csv'].name}: {n0}x{n1}={len(df)} pts, "
          f"success={np.sum(labels==1)} ({100*np.mean(labels==1):.1f}%)")
    return labels, n0, n1


def load_deepreach_csv(slice_name: str):
    """Load DeepReach CSV. Returns (pred_labels_flat, values_flat, n0, n1).

    pred_labels: {-1, 0, 1} = {uncertain, failure, success}
    """
    sl = SLICES[slice_name]
    df = pd.read_csv(sl["dr_csv"])
    ax0, ax1 = sl["dr_ax0_col"], sl["dr_ax1_col"]
    df = df.sort_values([ax0, ax1]).reset_index(drop=True)
    n0 = df[ax0].nunique()
    n1 = df[ax1].nunique()
    labels = df["pred_label"].values.astype(np.int8)
    values = df["value"].values.astype(np.float32)
    n_safe = np.sum(labels == 1)
    n_fail = np.sum(labels == 0)
    n_unc = np.sum(labels == -1)
    total = len(labels)
    print(f"  DeepReach {sl['dr_csv'].name}: {n0}x{n1}={total} pts, "
          f"success={n_safe} ({100*n_safe/total:.1f}%), "
          f"fail={n_fail} ({100*n_fail/total:.1f}%), "
          f"uncertain={n_unc} ({100*n_unc/total:.1f}%)")
    return labels, values, n0, n1


def load_olympics_cache(slice_name: str, epoch: int):
    """Load Olympics classifier cache. Returns dict[method_name] -> {pred_labels, ...} or None."""
    cf = OLYMPICS_CACHE_DIR / f"qualitative_cartpole_{slice_name}_cache.npz"
    if not cf.exists():
        print(f"  Olympics cache not found: {cf}")
        return None

    data = np.load(str(cf), allow_pickle=False)
    methods = {}
    for cache_key, display_name in _CACHE_KEY_MAP.items():
        prefix = f"{cache_key}_epoch{epoch}"
        key = f"{prefix}_pred"
        if key not in data:
            print(f"  Warning: {cache_key} epoch {epoch} not in cache, skipping")
            continue
        methods[display_name] = {
            "pred_labels": data[f"{prefix}_pred"],
            "p_success": data[f"{prefix}_psuc"],
            "lambda_star": float(data[f"{prefix}_lam"]),
            "delta_star": float(data[f"{prefix}_delta"]),
        }
    if not methods:
        return None
    print(f"  Olympics cache loaded: {list(methods.keys())}")
    return methods


# ═══════════════════════════════════════════════════════════════════════════════
# Plotting helpers
# ═══════════════════════════════════════════════════════════════════════════════

def _discrete_cmap():
    """Red / yellow / green for failure / uncertain / success."""
    colors = ["#d73027", "#fee08b", "#1a9850"]
    cmap = mcolors.ListedColormap(colors)
    bounds = [-1.5, -0.5, 0.5, 1.5]
    norm = mcolors.BoundaryNorm(bounds, cmap.N)
    return cmap, norm


def _gt_to_heatmap(gt_labels, n0, n1):
    return np.where(gt_labels == 1, 1.0, -1.0).reshape(n0, n1).T


def _pred_to_heatmap(pred, n0, n1):
    """Binary Olympics pred {0,1} -> discrete heatmap {-1, 1}."""
    heatmap = np.zeros_like(pred, dtype=float)
    heatmap[pred == 1] = 1
    heatmap[pred == 0] = -1
    return heatmap.reshape(n0, n1).T


def _3class_to_heatmap(labels, n0, n1):
    """3-class labels {-1, 0, 1} -> 2D heatmap."""
    return labels.astype(float).reshape(n0, n1).T


def _style_ax(ax, sl, fontsize=12):
    ax.set_xticks(sl["xticks"])
    ax.set_xticklabels(sl["xticklabels"], fontsize=fontsize, fontweight="bold")
    ax.set_yticks(sl["yticks"])
    ax.set_yticklabels(sl["yticklabels"], fontsize=fontsize, fontweight="bold")
    ax.tick_params(labelsize=fontsize)


def _ensure_dirs():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    FLAGSHIP_DIR.mkdir(parents=True, exist_ok=True)


def _save_fig(fig, base_name):
    _ensure_dirs()
    for ext, d in [("pdf", OUTPUT_DIR), ("png", FLAGSHIP_DIR)]:
        out = str(d / f"{base_name}.{ext}")
        fig.savefig(out, dpi=300, bbox_inches="tight")
        print(f"Saved {out}")


def _save_bare(heatmap_2d, extent, cmap, name, norm=None, vmin=None, vmax=None,
               interp="nearest"):
    """Save a single bare image -- no axis, no title."""
    fig, ax = plt.subplots(figsize=(4, 4))
    ax.imshow(
        heatmap_2d, origin="lower", aspect="auto",
        cmap=cmap, norm=norm, vmin=vmin, vmax=vmax,
        extent=extent, interpolation=interp,
    )
    ax.axis("off")
    fig.subplots_adjust(left=0, right=1, top=1, bottom=0)
    _ensure_dirs()
    fig.savefig(str(OUTPUT_DIR / f"{name}.pdf"), dpi=300,
                bbox_inches="tight", pad_inches=0)
    fig.savefig(str(FLAGSHIP_DIR / f"{name}.png"), dpi=300,
                bbox_inches="tight", pad_inches=0)
    print(f"  Saved bare: {name}")
    plt.close(fig)


# ═══════════════════════════════════════════════════════════════════════════════
# Error analysis
# ═══════════════════════════════════════════════════════════════════════════════

def _error_cmap():
    """TP(yellow) / TN(purple) / FP(green) / FN(blue) / Sep(gray)."""
    colors = ["#FDE725", "#440154", "#35B779", "#31688E", "#D3D3D3"]
    cmap = mcolors.ListedColormap(colors)
    bounds = [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]
    norm = mcolors.BoundaryNorm(bounds, cmap.N)
    return cmap, norm


def compute_error_map(gt_binary, pred_labels, failure_value):
    """Compute per-point error classification.

    Returns: 0=TP, 1=TN, 2=FP, 3=FN, 4=Separatrix
    """
    gt_success = (gt_binary == 1)
    pred_success = (pred_labels == 1)
    pred_failure = (pred_labels == failure_value)
    sep_mask = ~pred_success & ~pred_failure

    codes = np.empty(len(gt_binary), dtype=np.int8)
    codes[sep_mask] = 4
    codes[gt_success & pred_success] = 0
    codes[~gt_success & pred_failure] = 1
    codes[~gt_success & pred_success] = 2
    codes[gt_success & pred_failure] = 3
    return codes


def _print_error_stats(label, codes, total):
    tp = int(np.sum(codes == 0))
    tn = int(np.sum(codes == 1))
    fp = int(np.sum(codes == 2))
    fn = int(np.sum(codes == 3))
    sep = int(np.sum(codes == 4))
    gt_pos = tp + fn
    gt_neg = tn + fp
    fpr = fp / gt_neg * 100 if gt_neg > 0 else 0
    fnr = fn / gt_pos * 100 if gt_pos > 0 else 0
    print(f"    {label:25s}: TP={tp:6d} TN={tn:6d} FP={fp:6d} FN={fn:6d} "
          f"Sep={sep:6d} | FPR={fpr:.1f}% FNR={fnr:.1f}%")


# ═══════════════════════════════════════════════════════════════════════════════
# Individual bare heatmaps
# ═══════════════════════════════════════════════════════════════════════════════

def plot_bare_singles(all_data: dict, epoch: int):
    """Save individual bare heatmaps for each method/slice."""
    cmap, norm = _discrete_cmap()

    for slice_name, d in all_data.items():
        sl = SLICES[slice_name]
        extent = [*sl["sweep_ranges"][0], *sl["sweep_ranges"][1]]
        n0, n1 = d["n0"], d["n1"]

        # GT
        _save_bare(d["gt_heatmap"], extent, cmap,
                   f"csv_{slice_name}_ground_truth", norm=norm)

        # DeepReach
        if "deepreach_heatmap" in d:
            _save_bare(d["deepreach_heatmap"], extent, cmap,
                       f"csv_{slice_name}_deepreach", norm=norm)

        # Olympics methods
        if "olympics" in d:
            for method_name, mdata in d["olympics"].items():
                safe = method_name.replace(" ", "_").replace("(", "").replace(")", "")
                hm = _pred_to_heatmap(mdata["pred_labels"], n0, n1)
                _save_bare(hm, extent, cmap,
                           f"csv_{slice_name}_{safe}_ep{epoch}", norm=norm)


# ═══════════════════════════════════════════════════════════════════════════════
# Combined comparison plots
# ═══════════════════════════════════════════════════════════════════════════════

def _build_method_columns(all_data):
    """Build ordered list of (label, heatmap_getter) for available methods."""
    first = next(iter(all_data.values()))
    cols = []

    # Olympics methods (if available)
    if "olympics" in first:
        for method_name in first["olympics"]:
            cols.append({
                "label": method_name,
                "get_heatmap": lambda d, n0, n1, m=method_name: _pred_to_heatmap(
                    d["olympics"][m]["pred_labels"], n0, n1),
                "get_labels": lambda d, m=method_name: d["olympics"][m]["pred_labels"],
                "failure_value": 0,
            })

    # DeepReach
    if "deepreach_heatmap" in first:
        cols.append({
            "label": "DeepReach",
            "get_heatmap": lambda d, n0, n1: d["deepreach_heatmap"],
            "get_labels": lambda d: d["deepreach_labels"],
            "failure_value": 0,  # DeepReach pred_label: 0=failure, 1=success, -1=uncertain
        })

    return cols


def plot_combined_horizontal(all_data: dict, epoch: int):
    """Horizontal layout: rows=slices, cols=(GT + methods)."""
    slice_names = list(all_data.keys())
    method_cols = _build_method_columns(all_data)
    col_labels = ["Ground Truth"] + [c["label"] for c in method_cols]
    n_rows = len(slice_names)
    n_cols = len(col_labels)

    cmap, norm = _discrete_cmap()
    label_fs = 13
    tick_fs = 12

    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(3.5 * n_cols, 3.0 * n_rows),
        squeeze=False,
        constrained_layout=True,
    )

    for row, slice_name in enumerate(slice_names):
        sl = SLICES[slice_name]
        d = all_data[slice_name]
        extent = [*sl["sweep_ranges"][0], *sl["sweep_ranges"][1]]
        n0, n1 = d["n0"], d["n1"]

        # GT column
        ax = axes[row, 0]
        ax.imshow(d["gt_heatmap"], origin="lower", aspect="auto",
                  cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
        ax.set_xlabel(sl["xlabel"], fontsize=label_fs, fontweight="bold")
        ax.set_ylabel(sl["ylabel"], fontsize=label_fs, fontweight="bold")
        _style_ax(ax, sl, fontsize=tick_fs)

        # Method columns
        for col, mc in enumerate(method_cols, start=1):
            ax = axes[row, col]
            hm = mc["get_heatmap"](d, n0, n1)
            ax.imshow(hm, origin="lower", aspect="auto",
                      cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
            ax.set_xlabel(sl["xlabel"], fontsize=label_fs, fontweight="bold")
            ax.set_ylabel(sl["ylabel"], fontsize=label_fs, fontweight="bold")
            _style_ax(ax, sl, fontsize=tick_fs)

    # Column titles
    for col, label in enumerate(col_labels):
        axes[0, col].set_title(label, fontsize=14, fontweight="bold")

    # Legend
    from matplotlib.patches import Patch
    legend_patches = [
        Patch(facecolor="#1a9850", label="Success"),
        Patch(facecolor="#fee08b", label="Uncertain"),
        Patch(facecolor="#d73027", label="Failure"),
    ]
    fig.legend(
        handles=legend_patches, loc="lower center",
        ncol=3, fontsize=12, frameon=False, prop={"weight": "bold"},
        bbox_to_anchor=(0.5, -0.04),
    )

    _save_fig(fig, f"csv_comparison_horiz_ep{epoch}")
    plt.close(fig)


def plot_combined_vertical(all_data: dict, epoch: int):
    """Vertical layout (IROS): rows=(GT + methods), cols=slices."""
    slice_names = list(all_data.keys())
    method_cols = _build_method_columns(all_data)
    row_labels = ["Ground Truth"] + [c["label"] for c in method_cols]
    n_rows = len(row_labels)
    n_cols = len(slice_names)

    IROS_COL_WIDTH = 3.5
    cell_w = IROS_COL_WIDTH / n_cols
    cell_h = cell_w * 0.9
    fig_w = IROS_COL_WIDTH
    fig_h = cell_h * n_rows

    cmap, norm = _discrete_cmap()
    title_fs = 8
    label_fs = 7
    tick_fs = 6
    legend_fs = 7

    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(fig_w, fig_h),
        squeeze=False,
        constrained_layout=True,
    )

    for col_idx, slice_name in enumerate(slice_names):
        sl = SLICES[slice_name]
        d = all_data[slice_name]
        extent = [*sl["sweep_ranges"][0], *sl["sweep_ranges"][1]]
        n0, n1 = d["n0"], d["n1"]
        row = 0

        # GT row
        ax = axes[row, col_idx]
        ax.imshow(d["gt_heatmap"], origin="lower", aspect="auto",
                  cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
        ax.set_xlabel(sl["xlabel"], fontsize=label_fs, fontweight="bold")
        ax.set_ylabel(sl["ylabel"], fontsize=label_fs, fontweight="bold")
        _style_ax(ax, sl, fontsize=tick_fs)
        row += 1

        # Method rows
        for mc in method_cols:
            ax = axes[row, col_idx]
            hm = mc["get_heatmap"](d, n0, n1)
            ax.imshow(hm, origin="lower", aspect="auto",
                      cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
            ax.set_xlabel(sl["xlabel"], fontsize=label_fs, fontweight="bold")
            ax.set_ylabel(sl["ylabel"], fontsize=label_fs, fontweight="bold")
            _style_ax(ax, sl, fontsize=tick_fs)
            row += 1

    # Slice titles
    for col_idx, slice_name in enumerate(slice_names):
        short = (r"$(\theta,\,\dot{\theta})$" if "theta_thetadot" in slice_name
                 else r"$(x,\,\dot{x})$")
        axes[0, col_idx].set_title(short, fontsize=title_fs, fontweight="bold")

    # Row labels
    for row, label in enumerate(row_labels):
        axes[row, 0].annotate(
            label, xy=(0, 0.5), xytext=(-0.45, 0.5),
            xycoords="axes fraction", textcoords="axes fraction",
            fontsize=label_fs, fontweight="bold",
            ha="right", va="center", rotation=90,
        )

    from matplotlib.patches import Patch
    legend_patches = [
        Patch(facecolor="#1a9850", label="Success"),
        Patch(facecolor="#fee08b", label="Uncertain"),
        Patch(facecolor="#d73027", label="Failure"),
    ]
    fig.legend(
        handles=legend_patches, loc="lower center",
        ncol=3, fontsize=legend_fs, frameon=False, prop={"weight": "bold"},
        bbox_to_anchor=(0.5, -0.03),
    )

    _save_fig(fig, f"csv_comparison_vert_ep{epoch}")
    plt.close(fig)


# ═══════════════════════════════════════════════════════════════════════════════
# Error analysis plots
# ═══════════════════════════════════════════════════════════════════════════════

def plot_error_horizontal(all_data: dict, epoch: int):
    """Error analysis (horizontal): rows=slices, cols=(GT + methods)."""
    slice_names = list(all_data.keys())
    method_cols = _build_method_columns(all_data)
    col_labels = ["Ground Truth"] + [c["label"] for c in method_cols]
    n_rows = len(slice_names)
    n_cols = len(col_labels)

    cmap, norm = _error_cmap()
    label_fs = 8
    tick_fs = 7
    title_fs = 10

    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(1.8 * n_cols, 1.6 * n_rows),
        squeeze=False,
        gridspec_kw={"wspace": 0.05, "hspace": 0.05},
    )
    fig.subplots_adjust(left=0.10, right=0.98, top=0.90, bottom=0.14)

    for row, slice_name in enumerate(slice_names):
        sl = SLICES[slice_name]
        d = all_data[slice_name]
        extent = [*sl["sweep_ranges"][0], *sl["sweep_ranges"][1]]
        n0, n1 = d["n0"], d["n1"]
        gt = d["gt_labels"]
        is_bottom = (row == n_rows - 1)

        print(f"\n  Error analysis -- {slice_name}:")

        def _strip(ax, r, c):
            _style_ax(ax, sl, fontsize=tick_fs)
            if c == 0:
                ax.set_ylabel(sl["ylabel"], fontsize=label_fs, fontweight="bold")
            else:
                ax.set_ylabel("")
                ax.set_yticklabels([])
                ax.tick_params(left=False)
            if is_bottom:
                if c == 0:
                    ax.set_xlabel(sl["xlabel"], fontsize=label_fs, fontweight="bold")
                else:
                    ax.set_xlabel("")
            else:
                ax.set_xlabel("")
                ax.set_xticklabels([])
                ax.tick_params(bottom=False)

        # GT column
        gt_codes = np.where(gt == 1, 0, 1).astype(np.int8)
        ax = axes[row, 0]
        ax.imshow(gt_codes.reshape(n0, n1).T, origin="lower", aspect="auto",
                  cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
        _strip(ax, row, 0)
        _print_error_stats("Ground Truth", gt_codes, gt.size)

        # Method columns
        for col, mc in enumerate(method_cols, start=1):
            pred = mc["get_labels"](d)
            codes = compute_error_map(gt, pred, mc["failure_value"])
            ax = axes[row, col]
            ax.imshow(codes.reshape(n0, n1).T, origin="lower", aspect="auto",
                      cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
            _strip(ax, row, col)
            _print_error_stats(mc["label"], codes, gt.size)

    for col, label in enumerate(col_labels):
        axes[0, col].set_title(label, fontsize=title_fs, fontweight="bold")

    from matplotlib.patches import Patch
    legend_patches = [
        Patch(facecolor="#FDE725", label="TP"),
        Patch(facecolor="#440154", label="TN"),
        Patch(facecolor="#35B779", label="FP"),
        Patch(facecolor="#31688E", label="FN"),
        Patch(facecolor="#D3D3D3", label="Separatrix"),
    ]
    fig.legend(
        handles=legend_patches, loc="lower center",
        ncol=5, fontsize=9, frameon=False, prop={"weight": "bold"},
        bbox_to_anchor=(0.5, -0.06),
    )

    _save_fig(fig, f"csv_comparison_errors_horiz_ep{epoch}")
    plt.close(fig)


def plot_error_vertical(all_data: dict, epoch: int):
    """Error analysis (vertical): rows=(GT + methods), cols=slices."""
    slice_names = list(all_data.keys())
    method_cols = _build_method_columns(all_data)

    # Reorder: baselines first, then Olympics reversed
    bl_cols = [c for c in method_cols if c["failure_value"] != 0]
    ol_cols = [c for c in method_cols if c["failure_value"] == 0]
    ordered_cols = bl_cols + list(reversed(ol_cols))
    row_labels = ["Ground Truth"] + [c["label"] for c in ordered_cols]

    n_rows = len(row_labels)
    n_cols = len(slice_names)

    fig_w = 12
    cell_w = fig_w / n_cols
    cell_h = cell_w * 0.65
    fig_h = cell_h * n_rows

    cmap, norm = _error_cmap()
    title_fs = 20
    label_fs = 18
    tick_fs = 16

    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(fig_w, fig_h),
        squeeze=False,
        gridspec_kw={"wspace": 0.05, "hspace": 0.05},
    )
    fig.subplots_adjust(left=0.20, right=0.92, top=0.95, bottom=0.09)

    last_row = n_rows - 1

    for col_idx, slice_name in enumerate(slice_names):
        sl = SLICES[slice_name]
        d = all_data[slice_name]
        extent = [*sl["sweep_ranges"][0], *sl["sweep_ranges"][1]]
        n0, n1 = d["n0"], d["n1"]
        gt = d["gt_labels"]

        def _strip(ax, r, c):
            _style_ax(ax, sl, fontsize=tick_fs)
            if c == 0:
                ax.set_ylabel(sl["ylabel"], fontsize=label_fs, fontweight="bold")
            elif c == n_cols - 1:
                ax.yaxis.set_label_position("right")
                ax.yaxis.tick_right()
                ax.set_ylabel(sl["ylabel"], fontsize=label_fs, fontweight="bold")
            else:
                ax.set_ylabel("")
                ax.set_yticklabels([])
                ax.tick_params(left=False, right=False)
            if r == last_row:
                ax.set_xlabel(sl["xlabel"], fontsize=label_fs, fontweight="bold")
            else:
                ax.set_xlabel("")
                ax.set_xticklabels([])
                ax.tick_params(bottom=False)

        row = 0
        # GT row
        gt_codes = np.where(gt == 1, 0, 1).astype(np.int8)
        ax = axes[row, col_idx]
        ax.imshow(gt_codes.reshape(n0, n1).T, origin="lower", aspect="auto",
                  cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
        _strip(ax, row, col_idx)
        row += 1

        # Method rows
        for mc in ordered_cols:
            pred = mc["get_labels"](d)
            codes = compute_error_map(gt, pred, mc["failure_value"])
            ax = axes[row, col_idx]
            ax.imshow(codes.reshape(n0, n1).T, origin="lower", aspect="auto",
                      cmap=cmap, norm=norm, extent=extent, interpolation="nearest")
            _strip(ax, row, col_idx)
            row += 1

    # Slice titles
    for col_idx, slice_name in enumerate(slice_names):
        short = (r"$(\theta,\,\dot{\theta})$" if "theta_thetadot" in slice_name
                 else r"$(x,\,\dot{x})$")
        axes[0, col_idx].set_title(short, fontsize=title_fs, fontweight="bold")

    # Row labels
    method_fs = 20
    for row, label in enumerate(row_labels):
        axes[row, 0].annotate(
            label, xy=(0, 0.5), xytext=(-0.28, 0.5),
            xycoords="axes fraction", textcoords="axes fraction",
            fontsize=method_fs, fontweight="bold",
            ha="right", va="center", rotation=90,
        )

    from matplotlib.patches import Patch
    legend_patches = [
        Patch(facecolor="#FDE725", edgecolor="0.4", linewidth=0.5, label="TP"),
        Patch(facecolor="#440154", edgecolor="0.4", linewidth=0.5, label="TN"),
        Patch(facecolor="#35B779", edgecolor="0.4", linewidth=0.5, label="FP"),
        Patch(facecolor="#31688E", edgecolor="0.4", linewidth=0.5, label="FN"),
        Patch(facecolor="#D3D3D3", edgecolor="0.4", linewidth=0.5, label="Separatrix"),
    ]
    fig.legend(
        handles=legend_patches, loc="lower center",
        ncol=5, fontsize=18, frameon=False, prop={"weight": "bold", "size": 18},
        bbox_to_anchor=(0.56, -0.01), handletextpad=0.5, columnspacing=1.0,
        handleheight=1.5, handlelength=2.0,
    )

    _save_fig(fig, f"csv_comparison_errors_vert_ep{epoch}")
    plt.close(fig)


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Combined CartPole comparison from CSV files"
    )
    parser.add_argument("--epoch", type=int, default=DEFAULT_EPOCH,
                        help="Olympics epoch (default: 15)")
    parser.add_argument("--slice", default="theta_thetadot",
                        choices=list(SLICES.keys()))
    parser.add_argument("--all_slices", action="store_true",
                        help="Use both slices")
    parser.add_argument("--no_olympics", action="store_true",
                        help="Skip Olympics classifier (no cache needed)")
    parser.add_argument("--no_errors", action="store_true",
                        help="Skip FP/FN error analysis plots")
    args = parser.parse_args()

    slice_names = list(SLICES.keys()) if args.all_slices else [args.slice]

    # ── Load all data ─────────────────────────────────────────────────────
    all_data = {}

    for slice_name in slice_names:
        print(f"\n{'='*60}")
        print(f"Slice: {slice_name}")
        print(f"{'='*60}")

        # Ground truth
        gt_labels, n0, n1 = load_gt_csv(slice_name)
        gt_heatmap = _gt_to_heatmap(gt_labels, n0, n1)

        entry = {
            "gt_heatmap": gt_heatmap,
            "gt_labels": gt_labels,
            "n0": n0, "n1": n1,
        }

        # DeepReach
        dr_labels, dr_values, dn0, dn1 = load_deepreach_csv(slice_name)
        assert dn0 == n0 and dn1 == n1, (
            f"Grid mismatch: GT {n0}x{n1} vs DeepReach {dn0}x{dn1}")
        entry["deepreach_heatmap"] = _3class_to_heatmap(dr_labels, n0, n1)
        entry["deepreach_labels"] = dr_labels

        # Olympics (optional)
        if not args.no_olympics:
            olympics = load_olympics_cache(slice_name, args.epoch)
            if olympics:
                entry["olympics"] = olympics

        all_data[slice_name] = entry

    # ── Generate plots ────────────────────────────────────────────────────
    print("\nGenerating individual bare heatmaps...")
    plot_bare_singles(all_data, args.epoch)

    print("\nGenerating combined horizontal comparison...")
    plot_combined_horizontal(all_data, args.epoch)

    print("\nGenerating combined vertical comparison...")
    plot_combined_vertical(all_data, args.epoch)

    if not args.no_errors:
        print("\nGenerating error analysis plots...")
        plot_error_horizontal(all_data, args.epoch)
        plot_error_vertical(all_data, args.epoch)

    print("\nDone.")


if __name__ == "__main__":
    main()
