#!/usr/bin/env python
"""Recompute the §7 standings tables and write them into the quadrotor READMEs.

Run this every monitoring cycle, right after scripts/score_stoch_incremental.py and
the figure regeneration, so the prose never lags the CSVs. It is idempotent: the
tables live between HTML-comment markers and are replaced wholesale each run.

Floor convention (pre-registered, do not change without re-deriving every table):
  2 * sqrt(mean over shared epochs of the 3-seed variance), epoch 0 EXCLUDED.
Metrics are KL, debiased Brier and sAUROC -- never the artifact AUC/Brier, which
score against a 0.5-dichotomised truth.

An arm is compared at its own deepest epoch against the 3-seed control at the same
epoch when available, else at the control's deepest shared epoch (flagged in the
note under the table). Verdicts report better AND worse counts separately: an arm
that ranks well but calibrates badly must not read as a win.
"""
import argparse, collections, csv, math, pathlib, statistics as st

ROOT = pathlib.Path(__file__).resolve().parent.parent
D2D = pathlib.Path("/common/users/shared/pracsys/genMoPlan/docs/stochastic/quadrotor2d")
D3D = pathlib.Path("/common/users/shared/pracsys/genMoPlan/docs/stochastic/quadrotor3d")

SEEDS = ["dir00_s42", "dir00_s43", "dir00_s44"]
COLS = [("KL", "KL"), ("brier_debiased", "Brier_deb"), ("sAUROC", "sAUROC")]
LOWER_IS_BETTER = {"KL": True, "brier_debiased": True, "sAUROC": False}

# readme -> list of (csv, level key, heading, n_epochs)
TARGETS = {
    D2D / "README.md": [
        (D2D / "quad2d_noisy_dynamics_all_levels.csv", "noisy_dynamics_f_0.150",
         "quad2D `noisy_dynamics f_0.150`", 24),
        (D2D / "quad2d_corridor_sine_ambient_all_levels.csv", "corridor_sine_ambient_smooth",
         "quad2D `corridor_sine_ambient smooth`", 24),
    ],
    D3D / "README.md": [
        (D3D / "quad3d_noisy_dynamics_all_levels.csv", "noisy_dynamics_f_0.048",
         "quad3D `noisy_dynamics f_0.048` (PAUSED)", 18),
        (D3D / "quad3d_noisy_dynamics_all_levels.csv", "noisy_dynamics_f_0.060",
         "quad3D `noisy_dynamics f_0.060` (PAUSED)", 18),
        (D3D / "quad3d_corridor_sine_ambient_all_levels.csv", "corridor_sine_ambient_f_0.30",
         "quad3D `corridor_sine_ambient f_0.30`", 18),
    ],
}

BEGIN = "<!-- STANDINGS:BEGIN (generated by scripts/update_standings.py -- do not hand-edit) -->"
END = "<!-- STANDINGS:END -->"


def load(path, level):
    d = collections.defaultdict(dict)
    if not path.exists():
        return d
    for r in csv.DictReader(open(path)):
        if r["level"] == level:
            d[r["arm"]][int(r["epoch"])] = r
    return d


def render(path, level, heading, n_epochs):
    d = load(path, level)
    arms = [a for a in d if a not in SEEDS]
    n_done = sum(1 for a in d if len(d[a]) == n_epochs)
    total = sum(len(v) for v in d.values())
    out = [f"\n### {heading} — {total}/{14 * n_epochs} epochs, {n_done}/14 arms complete\n"]

    if not d:
        out.append("_No rows yet._\n")
        return "\n".join(out)

    have = [s for s in SEEDS if s in d]
    if len(have) < 3:
        out.append(f"_Only {len(have)}/3 uniform floor seeds have rows "
                   f"({', '.join(have) or 'none'}), so no 2·SD floor is computable yet. "
                   f"Per-arm depth: " +
                   ", ".join(f"`{a}` {max(d[a]) + 1}" for a in sorted(d)) + "._\n")
        return "\n".join(out)

    shared = sorted(set.intersection(*[set(d[s]) for s in have]) - {0})
    if not shared:
        out.append("_Floor seeds share no epoch beyond ep0 yet._\n")
        return "\n".join(out)
    last = max(shared)

    fl, ctl = {}, {}
    for c, _ in COLS:
        fl[c] = 2 * math.sqrt(
            sum(st.variance([float(d[s][e][c]) for s in have]) for e in shared) / len(shared))
        ctl[c] = st.mean([float(d[s][last][c]) for s in have])

    out.append(f"| metric | 2·SD floor (ep{shared[0]}–{shared[-1]}) | "
               f"3-seed uniform control at ep{last} |")
    out.append("|---|---|---|")
    for c, lab in COLS:
        out.append(f"| {lab} | **{fl[c]:.4f}** | {ctl[c]:.4f} |")
    out.append("")
    out.append("| arm | ep | KL | Brier_deb | sAUROC | ΔKL | ΔBrier | ΔsAUROC | verdict |")
    out.append("|---|---|---|---|---|---|---|---|---|")

    rows, shallow = [], []
    for arm in arms:
        ep = max(d[arm])
        cmp_ep = ep if ep <= last else last
        if ep != cmp_ep:
            shallow.append(arm)
        r = d[arm][cmp_ep]
        v = {c: float(r[c]) for c, _ in COLS}
        dl = {c: v[c] - ctl[c] for c, _ in COLS}
        b = w = 0
        for c, _ in COLS:
            s = -1 if LOWER_IS_BETTER[c] else 1
            if s * dl[c] > fl[c]:
                b += 1
            elif s * dl[c] < -fl[c]:
                w += 1
        if b and w:
            verd = f"**mixed — better ×{b}, worse ×{w}**"
        elif b == 3:
            verd = "beats floor ×3"
        elif b:
            verd = f"beats floor ×{b}"
        elif w == 3:
            verd = "**worse than uniform ×3**"
        elif w:
            verd = f"**worse ×{w}**"
        else:
            verd = "inside floor"
        rows.append((v["KL"], arm, cmp_ep, v, dl, verd))

    for _, arm, ep, v, dl, verd in sorted(rows):
        out.append(f"| `{arm}` | {ep} | {v['KL']:.4f} | {v['brier_debiased']:.4f} | "
                   f"{v['sAUROC']:.4f} | {dl['KL']:+.4f} | {dl['brier_debiased']:+.4f} | "
                   f"{dl['sAUROC']:+.4f} | {verd} |")
    out.append("")
    if shallow:
        out.append(f"> Compared at ep{last}, the control's deepest shared epoch. "
                   f"These arms are deeper than that and are read at ep{last} rather than "
                   f"their own deepest: " + ", ".join(f"`{a}`" for a in sorted(shallow)) + ".")
        out.append("")
    if n_done < 14:
        out.append(f"> Level incomplete ({n_done}/14 arms at {n_epochs} epochs). Ordering can "
                   f"still move; treat as provisional.")
        out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any README would change (no write)")
    a = ap.parse_args()
    changed = []
    for readme, specs in TARGETS.items():
        if not readme.exists():
            continue
        body = "\n".join(render(*s) for s in specs)
        block = f"{BEGIN}\n{body}\n{END}"
        s = readme.read_text()
        if BEGIN in s and END in s:
            new = s[:s.index(BEGIN)] + block + s[s.index(END) + len(END):]
        else:  # first run: append at the end of §7, before Companion documents
            marker = "## Companion documents"
            i = s.index(marker) if marker in s else len(s)
            new = s[:i] + block + "\n\n" + s[i:]
        if new != s:
            changed.append(readme.name)
            if not a.check:
                readme.write_text(new)
        print(f"  {readme.parent.name}/{readme.name}: "
              f"{'WOULD CHANGE' if a.check and new != s else ('updated' if new != s else 'already current')}")
    if a.check and changed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
