# @package _global_

defaults:
  - _base
  - /model/system_dims: cartpole_pybullet
  - _self_

name: adaptive_cartpole_pybullet
output_dir: ${exp_dir}/${name}/outputs/training_index_${training_index}_warm_start_${warm_start}_manifold_${use_manifold}_adapt_iter_${n_epochs}/${now:%Y-%m-%d_%H-%M-%S}

decision_rule: two_sided
attractor_radius: 0.2

threshold:
  optimize_mode: joint

data_source:
  base_dir: ${data_dir}/cartpole_pybullet
  trajectories_dir: ${data_source.base_dir}/trajectories
  train_test_splits_dir: ${data_source.base_dir}/train_test_splits
  shuffled_indices_file: ${data_source.train_test_splits_dir}/shuffled_indices_${training_index}.txt
  shuffled_labels_file: ${data_source.train_test_splits_dir}/shuffled_labels_${training_index}.txt
  eval_states_file: ${data_source.base_dir}/eval_states.txt
  cal_set_file: ${data_source.base_dir}/cal_set.txt
  test_set_file: ${data_source.base_dir}/test_set.txt

initial_train_size: 300
n_epochs: 15

flow_matching:
  clamp_noise: false

system:
  _target_: adaptive_roa.systems.cartpole.CartPoleSystem
  dataset_dir: ${data_dir}/cartpole_pybullet

flow_matcher:
  _target_: adaptive_roa.flow_matching.cartpole.latent_conditional.flow_matcher.CartPoleLatentConditionalFlowMatcher

flow_matcher_local:
  _target_: adaptive_roa.flow_matching.cartpole.trajectory.flow_matcher.CartPoleTrajectoryFlowMatcher

adaptive_v2:
  system_name: cartpole_pybullet
