# @package _global_

defaults:
  - _base
  - /model/system_dims: quadrotor3d
  - /prediction_mode: global
  - _self_

name: adaptive_quadrotor3d
output_dir: ${exp_dir}/${name}/outputs/training_index_${training_index}_warm_start_${warm_start}_manifold_${use_manifold}_adapt_iter_${n_epochs}/${now:%Y-%m-%d_%H-%M-%S}

decision_rule: two_sided
attractor_radius: 0.3

use_log_loss_weights: true

dataset_name: quadrotor3D_lqr
dataset_root: ${data_dir}/${noise_regime}/${dataset_name}

data_source:
  base_dir: ${dataset_root}
  trajectories_dir: ${data_source.base_dir}/trajectories
  train_test_splits_dir: ${data_source.base_dir}/train_test_splits
  shuffled_indices_file: ${data_source.train_test_splits_dir}/all_shuffled_indices.txt
  shuffled_labels_file: ${data_source.train_test_splits_dir}/all_shuffled_labels.txt
  eval_states_file: ${data_source.base_dir}/eval_states.txt
  cal_set_file: ${data_source.base_dir}/cal_set.txt
  test_set_file: ${data_source.base_dir}/test_set.txt

initial_train_size: 2000
n_epochs: 30
samples_per_epoch: 500

flow_matching:
  clamp_noise: false
  quat_loss_weight: ${quat_loss_weight}

optimizer:
  lr: 5e-4

system:
  _target_: adaptive_roa.systems.quadrotor3d.Quadrotor3DSystem
  dataset_dir: ${dataset_root}

flow_matcher:
  _target_: adaptive_roa.flow_matching.quadrotor_3d.latent_conditional.flow_matcher.Quadrotor3DLatentConditionalFlowMatcher

flow_matcher_local:
  _target_: adaptive_roa.flow_matching.quadrotor_3d.trajectory.flow_matcher.Quadrotor3DTrajectoryFlowMatcher

adaptive_v2:
  system_name: quadrotor3d
